DROP TABLE IF EXISTS item_tags CASCADE;
DROP TABLE IF EXISTS shares CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS app_events CASCADE;
DROP TABLE IF EXISTS users CASCADE;
